name: Bot Python

on:
  push:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        if: exists('requirements.txt')
        run: |
          pip install -r requirements.txt

      - name: Rodar bot
        run: |
          python bot.py
